### ISSUE TITLE
请问下在TLS Enabled的情况下的问题

### ISSUE THREAD

**Issue by will-hu-0** [qiushaoxi/fabric-in-swarm#1]
你好，在看yaml中，看到这句话：

> # peer启动的chaincode运行环境是通过 unix:///host/var/run/docker.sock 启动的，脱离在docker stack 外部。所以需要给外部访问地址才能和peer联通

这个没有问题。我们现在的问题是Enable TLS下，会出现无法在new chaincode那个容器中，无法和peer连通。请问 这个有解吗？

**Comment by will-hu-0** [comment]
后面我们解决了这个问题，用1.0.6的版本，

```
networks:
  yourNetwork:
    driver: overlay
    attachable: true

services:
  orderer:.........
     networks:
      yourNetwork:
        aliases:
        - orderer.example.com 


  peer0
     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=sample_yourNetwork
     - CORE_PEER_ADDRESS=peer0.org1.example:7051
      networks:
        yourNetwork:
          aliases:
          - peer0.org1.example.com

  cli:
     - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=sample_yourNetwork
      networks:
        - yourNetwork:
          aliases:
          - peer0.org1.example.com
```
And finally deploy it by

```docker stack deploy -c docker-compose.yaml sample```
Please be noted by the naming of the network (Prefix)
